version: 2
jobs:
  test:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/tmc/circleci
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: go get -t ./...
      - run: go get github.com/jstemmer/go-junit-report
      - run:
          name: tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test -v ./... | tee ${TEST_RESULTS}/go-test.out

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
  lint:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/tmc/circleci

    steps:
      - checkout

      - run: go get -t ./...
      - run: go get -u golang.org/x/lint/golint
      - run: go vet ./...
      - run: golint ./...

workflows:
  version: 2
  ci:
    jobs:
      - test
      - lint
